language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
env:
  - DIGITAL_OCEAN_CLIENT_ID=123456789 DIGITAL_OCEAN_API_KEY=fedcba9876543210
before_install:
  - gem install bundler
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
